export const COUNTRY_DATA: Record<string, { flag: string; dialCode: string; minLength: number; maxLength: number; code: string }> = {
  "Nigeria": { flag: "🇳🇬", dialCode: "+234", minLength: 10, maxLength: 10, code: "NG" },
  "Ghana": { flag: "🇬🇭", dialCode: "+233", minLength: 9, maxLength: 9, code: "GH" },
  "Kenya": { flag: "🇰🇪", dialCode: "+254", minLength: 9, maxLength: 9, code: "KE" },
  "South Africa": { flag: "🇿🇦", dialCode: "+27", minLength: 9, maxLength: 9, code: "ZA" },
  "The Gambia": { flag: "🇬🇲", dialCode: "+220", minLength: 7, maxLength: 7, code: "GM" },
  "Tanzania": { flag: "🇹🇿", dialCode: "+255", minLength: 9, maxLength: 9, code: "TZ" },
  "Uganda": { flag: "🇺🇬", dialCode: "+256", minLength: 9, maxLength: 9, code: "UG" },
  "Zambia": { flag: "🇿🇲", dialCode: "+260", minLength: 9, maxLength: 9, code: "ZM" },
  "Zimbabwe": { flag: "🇿🇼", dialCode: "+263", minLength: 9, maxLength: 9, code: "ZW" },
  "Botswana": { flag: "🇧🇼", dialCode: "+267", minLength: 8, maxLength: 8, code: "BW" },
  "Liberia": { flag: "🇱🇷", dialCode: "+231", minLength: 7, maxLength: 7, code: "LR" },
  "Sierra Leone": { flag: "🇸🇱", dialCode: "+232", minLength: 8, maxLength: 8, code: "SL" },
  "Algeria": { flag: "🇩🇿", dialCode: "+213", minLength: 9, maxLength: 9, code: "DZ" },
  "Angola": { flag: "🇦🇴", dialCode: "+244", minLength: 9, maxLength: 9, code: "AO" },
  "Benin": { flag: "🇧🇯", dialCode: "+229", minLength: 8, maxLength: 8, code: "BJ" },
  "Burkina Faso": { flag: "🇧🇫", dialCode: "+226", minLength: 8, maxLength: 8, code: "BF" },
  "Burundi": { flag: "🇧🇮", dialCode: "+257", minLength: 8, maxLength: 8, code: "BI" },
  "Cabo Verde": { flag: "🇨🇻", dialCode: "+238", minLength: 7, maxLength: 7, code: "CV" },
  "Cameroon": { flag: "🇨🇲", dialCode: "+237", minLength: 9, maxLength: 9, code: "CM" },
  "Chad": { flag: "🇹🇩", dialCode: "+235", minLength: 8, maxLength: 8, code: "TD" },
  "Egypt": { flag: "🇪🇬", dialCode: "+20", minLength: 10, maxLength: 10, code: "EG" },
  "Ethiopia": { flag: "🇪🇹", dialCode: "+251", minLength: 9, maxLength: 9, code: "ET" },
  "Morocco": { flag: "🇲🇦", dialCode: "+212", minLength: 9, maxLength: 9, code: "MA" },
  "Rwanda": { flag: "🇷🇼", dialCode: "+250", minLength: 9, maxLength: 9, code: "RW" },
  "Senegal": { flag: "🇸🇳", dialCode: "+221", minLength: 9, maxLength: 9, code: "SN" },
  "Tunisia": { flag: "🇹🇳", dialCode: "+216", minLength: 8, maxLength: 8, code: "TN" },
  "Central African Republic": { flag: "🇨🇫", dialCode: "+236", minLength: 8, maxLength: 8, code: "CF" },
  "Comoros": { flag: "🇰🇲", dialCode: "+269", minLength: 7, maxLength: 7, code: "KM" },
  "Congo": { flag: "🇨🇬", dialCode: "+242", minLength: 9, maxLength: 9, code: "CG" },
  "Democratic Republic of the Congo": { flag: "🇨🇩", dialCode: "+243", minLength: 9, maxLength: 9, code: "CD" },
  "Côte d'Ivoire": { flag: "🇨🇮", dialCode: "+225", minLength: 8, maxLength: 8, code: "CI" },
  "Djibouti": { flag: "🇩🇯", dialCode: "+253", minLength: 8, maxLength: 8, code: "DJ" },
  "Equatorial Guinea": { flag: "🇬🇶", dialCode: "+240", minLength: 9, maxLength: 9, code: "GQ" },
  "Eritrea": { flag: "🇪🇷", dialCode: "+291", minLength: 7, maxLength: 7, code: "ER" },
  "Eswatini": { flag: "🇸🇿", dialCode: "+268", minLength: 8, maxLength: 8, code: "SZ" },
  "Gabon": { flag: "🇬🇦", dialCode: "+241", minLength: 7, maxLength: 7, code: "GA" },
  "Guinea": { flag: "🇬🇳", dialCode: "+224", minLength: 9, maxLength: 9, code: "GN" },
  "Guinea-Bissau": { flag: "🇬🇼", dialCode: "+245", minLength: 7, maxLength: 7, code: "GW" },
  "Lesotho": { flag: "🇱🇸", dialCode: "+266", minLength: 8, maxLength: 8, code: "LS" },
  "Libya": { flag: "🇱🇾", dialCode: "+218", minLength: 9, maxLength: 9, code: "LY" },
  "Madagascar": { flag: "🇲🇬", dialCode: "+261", minLength: 9, maxLength: 9, code: "MG" },
  "Malawi": { flag: "🇲🇼", dialCode: "+265", minLength: 9, maxLength: 9, code: "MW" },
  "Mali": { flag: "🇲🇱", dialCode: "+223", minLength: 8, maxLength: 8, code: "ML" },
  "Mauritania": { flag: "🇲🇷", dialCode: "+222", minLength: 8, maxLength: 8, code: "MR" },
  "Mauritius": { flag: "🇲🇺", dialCode: "+230", minLength: 8, maxLength: 8, code: "MU" },
  "Mozambique": { flag: "🇲🇿", dialCode: "+258", minLength: 9, maxLength: 9, code: "MZ" },
  "Namibia": { flag: "🇳🇦", dialCode: "+264", minLength: 9, maxLength: 9, code: "NA" },
  "Niger": { flag: "🇳🇪", dialCode: "+227", minLength: 8, maxLength: 8, code: "NE" },
  "Sao Tome and Principe": { flag: "🇸🇹", dialCode: "+239", minLength: 7, maxLength: 7, code: "ST" },
  "Seychelles": { flag: "🇸🇨", dialCode: "+248", minLength: 7, maxLength: 7, code: "SC" },
  "Somalia": { flag: "🇸🇴", dialCode: "+252", minLength: 8, maxLength: 8, code: "SO" },
  "South Sudan": { flag: "🇸🇸", dialCode: "+211", minLength: 9, maxLength: 9, code: "SS" },
  "Sudan": { flag: "🇸🇩", dialCode: "+249", minLength: 9, maxLength: 9, code: "SD" },
  "Togo": { flag: "🇹🇬", dialCode: "+228", minLength: 8, maxLength: 8, code: "TG" },
  "United Arab Emirates": { flag: "🇦🇪", dialCode: "+971", minLength: 9, maxLength: 9, code: "AE" },
  "Saudi Arabia": { flag: "🇸🇦", dialCode: "+966", minLength: 9, maxLength: 9, code: "SA" },
  "Singapore": { flag: "🇸🇬", dialCode: "+65", minLength: 8, maxLength: 8, code: "SG" },
  "United States": { flag: "🇺🇸", dialCode: "+1", minLength: 10, maxLength: 10, code: "US" },
  "Canada": { flag: "🇨🇦", dialCode: "+1", minLength: 10, maxLength: 10, code: "CA" },
  "Jamaica": { flag: "🇯🇲", dialCode: "+1", minLength: 10, maxLength: 10, code: "JM" },
  "Trinidad and Tobago": { flag: "🇹🇹", dialCode: "+1", minLength: 10, maxLength: 10, code: "TT" },
  "United Kingdom": { flag: "🇬🇧", dialCode: "+44", minLength: 10, maxLength: 10, code: "GB" },
  "Germany": { flag: "🇩🇪", dialCode: "+49", minLength: 10, maxLength: 10, code: "DE" },
  "France": { flag: "🇫🇷", dialCode: "+33", minLength: 9, maxLength: 9, code: "FR" },
  "Netherlands": { flag: "🇳🇱", dialCode: "+31", minLength: 9, maxLength: 9, code: "NL" },
  "Ireland": { flag: "🇮🇪", dialCode: "+353", minLength: 9, maxLength: 9, code: "IE" },
  "Italy": { flag: "🇮🇹", dialCode: "+39", minLength: 10, maxLength: 10, code: "IT" },
  "Spain": { flag: "🇪🇸", dialCode: "+34", minLength: 9, maxLength: 9, code: "ES" },
  "Brazil": { flag: "🇧🇷", dialCode: "+55", minLength: 10, maxLength: 10, code: "BR" },
  "Colombia": { flag: "🇨🇴", dialCode: "+57", minLength: 10, maxLength: 10, code: "CO" },
  "Argentina": { flag: "🇦🇷", dialCode: "+54", minLength: 10, maxLength: 10, code: "AR" },
  "India": { flag: "🇮🇳", dialCode: "+91", minLength: 10, maxLength: 10, code: "IN" },
  "China": { flag: "🇨🇳", dialCode: "+86", minLength: 11, maxLength: 11, code: "CN" },
  "Japan": { flag: "🇯🇵", dialCode: "+81", minLength: 10, maxLength: 10, code: "JP" },
  "Australia": { flag: "🇦🇺", dialCode: "+61", minLength: 9, maxLength: 9, code: "AU" },
  "New Zealand": { flag: "🇳🇿", dialCode: "+64", minLength: 9, maxLength: 9, code: "NZ" },
};

// Default mapping for countries not fully defined
export const getCountryInfo = (name: string) => {
  return COUNTRY_DATA[name] || { flag: "🏳️", dialCode: "", minLength: 7, maxLength: 15, code: "" };
};
